name: whollet_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  get: ^4.6.6
  http: ^1.2.1
  http_interceptor: ^2.0.0
  flutter_screenutil: ^5.9.0
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  intl:

flutter:
  uses-material-design: true
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Light.ttf
          weight: 300
        - asset: assets/fonts/TitilliumWeb-ExtraLightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
          weight: 400
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/TitilliumWeb-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
          weight: 700
        - asset: assets/fonts/TitilliumWeb-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/TitilliumWeb-Black.ttf
          weight: 900

flutter_intl:
  enabled: true
  class_name: WholletLocalization
  main_locale: en
  arb_dir: lib/app/localization/l10n
  output_dir: lib/app/localization/generated
  use_deferred_loading: true
