name: whollet_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Light.ttf
          weight: 300
        - asset: assets/fonts/TitilliumWeb-ExtraLightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
          weight: 400
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/TitilliumWeb-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
          weight: 700
        - asset: assets/fonts/TitilliumWeb-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/TitilliumWeb-Black.ttf
          weight: 900